apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 429367298871.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:95528ca615af56789abcca3b5028a8acd0f4aeda
        ports:
        - containerPort: 80
