apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 429367298871.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:c8d49cd6fcc9d66afdaaaf500112b034eb28a0b1
        ports:
        - containerPort: 80
