apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:beed4449ab4892961799242d1aa68b8778ff5d82
        ports:
        - containerPort: 80
